-- DBTYPE=MYSQL

CREATE TABLE T_ACTIVITY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SHORT_NAME VARCHAR(20) NOT NULL
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE T_PLACE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SHORT_NAME VARCHAR(20) NOT NULL
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE T_SCHEDULE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    UPDATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TEACHER_ID BIGINT NOT NULL,
    RECEIVER_ID BIGINT NOT NULL,
    SUBJECT_ID BIGINT NOT NULL,
    PLACE_ID BIGINT NOT NULL,
    START_DT TIMESTAMP NULL,
    END_DT TIMESTAMP NULL,
    DOW VARCHAR(10) NULL,
    REPEAT_TYPE VARCHAR(10) NULL,
    START_TIME INT NULL,
    END_TIME INT NULL,
    SENT INT NOT NULL DEFAULT 0,
    CHECKED INT NOT NULL DEFAULT 0
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE T_SCHEDULE_ACTIVITY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SCHEDULE_ID BIGINT NOT NULL,
    ACTIVITY_ID BIGINT NOT NULL
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE T_SCHEDULE_DATE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ITEM_TYPE VARCHAR(10) NOT NULL,
    SCHEDULE_ID BIGINT NOT NULL,
    DT TIMESTAMP NOT NULL
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE T_SCHEDULE_GROUP (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SCHEDULE_ID BIGINT NOT NULL,
    GROUP_ID BIGINT NOT NULL
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE T_SESSION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USR_ID BIGINT NOT NULL,
    APP_NAME VARCHAR(100) NOT NULL DEFAULT 'auth',
    BEGIN_SESSION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    END_SESSION TIMESTAMP NULL,
    TOKEN VARCHAR(100) NULL
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE T_STUD_GROUP (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SPEC_CODE VARCHAR(20) NOT NULL,
    YEAR INT NOT NULL,
    NAME_CODE VARCHAR(20) NOT NULL,
    FULLTIME INT NOT NULL,
    SHORT INT NOT NULL,
    GRAD_TYPE INT NOT NULL
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE T_SUBJECT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SHORT_NAME VARCHAR(20) NOT NULL
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE T_USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PASS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(40) NULL,
    LOGIN VARCHAR(40) NULL,
    STATUS BIGINT NOT NULL DEFAULT 1,
    FACULT BIGINT NOT NULL DEFAULT 1,
    IS_SUPERUSER BIGINT NOT NULL DEFAULT 0,
    PHONE VARCHAR(40) NULL
    , PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE T_SCHEDULE ADD FOREIGN KEY (TEACHER_ID) REFERENCES T_USER(ID);
ALTER TABLE T_SCHEDULE ADD FOREIGN KEY (RECEIVER_ID) REFERENCES T_USER(ID);
ALTER TABLE T_SCHEDULE ADD FOREIGN KEY (SUBJECT_ID) REFERENCES T_SUBJECT(ID);
ALTER TABLE T_SCHEDULE ADD FOREIGN KEY (PLACE_ID) REFERENCES T_PLACE(ID);
ALTER TABLE T_SCHEDULE_ACTIVITY ADD FOREIGN KEY (SCHEDULE_ID) REFERENCES T_SCHEDULE(ID);
ALTER TABLE T_SCHEDULE_ACTIVITY ADD FOREIGN KEY (ACTIVITY_ID) REFERENCES T_ACTIVITY(ID);
ALTER TABLE T_SCHEDULE_DATE ADD FOREIGN KEY (SCHEDULE_ID) REFERENCES T_SCHEDULE(ID);
ALTER TABLE T_SCHEDULE_GROUP ADD FOREIGN KEY (SCHEDULE_ID) REFERENCES T_SCHEDULE(ID);
ALTER TABLE T_SCHEDULE_GROUP ADD FOREIGN KEY (GROUP_ID) REFERENCES T_STUD_GROUP(ID);
ALTER TABLE T_SESSION ADD FOREIGN KEY (USR_ID) REFERENCES T_USER(ID);
